### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by BertramShell** [dzt/supreme-api#6]
Hello When trying to call the watch for new items this pops out.

supreme.onNewItem(5, (product, err) => {
      if (err) {
         console.log(err);
         return err;
      }
      console.log('New Release: ' + item.name);
}); 

TypeError: callback is not a function
    /node_modules/supreme-api/index.js:227:13
    at Request._callback /node_modules/supreme-api/index.js:52:22)
    at Request.self.callback 
node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> 
node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> 
node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)

Thanks for the awsom api 👍

**Comment by AndreiTuta** [comment]
Having exactly the same problem.Any solution?

**Comment by AndreiTuta** [comment]
Still no update?Or at least a working api call?

**Comment by kingfly55** [comment]
im having same problem...

**Comment by Logfro** [comment]
https://github.com/Logfro/supreme-api <--- Working version

**Comment by kingfly55** [comment]
i got the same error with that version....

**Comment by kingfly55** [comment]
Oh i see, onNewItem hasnt been created yet.
